name: Build JOSS Paper

on:
  push:
    paths:
      - paper/paper.md
      - paper/paper.bib
      - .github/workflows/joss-paper.yml
  pull_request:
    paths:
      - paper/paper.md
      - paper/paper.bib
      - .github/workflows/joss-paper.yml
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Build JOSS Paper
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build paper
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
          
      - name: Upload paper PDF
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper
          path: paper/paper.pdf
          
      - name: Upload paper log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: paper-build-log
          path: paper/paper.log