name: Release

on:
  push:
    branches: [main]
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release-rust:
    name: Release Rust Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zip
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            archive: tar.gz
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Build release binary
        run: cargo build --release --bin iscc-sum --target ${{ matrix.target }}
      
      - name: Package binary (Unix)
        if: matrix.archive == 'tar.gz'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf iscc-sum-${{ matrix.target }}.tar.gz iscc-sum
          mv iscc-sum-${{ matrix.target }}.tar.gz ../../../
      
      - name: Package binary (Windows)
        if: matrix.archive == 'zip'
        shell: pwsh
        run: |
          cd target/${{ matrix.target }}/release
          Compress-Archive -Path iscc-sum.exe -DestinationPath iscc-sum-${{ matrix.target }}.zip
          Move-Item iscc-sum-${{ matrix.target }}.zip ../../../
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iscc-sum-${{ matrix.target }}
          path: iscc-sum-${{ matrix.target }}.${{ matrix.archive }}

  release-python:
    name: Build Python Wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          CIBW_BUILD: cp310-* cp311-* cp312-* cp313-*
          CIBW_SKIP: "*-musllinux_* *-win32 *-manylinux_i686"
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_LINUX: x86_64 aarch64
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_BEFORE_BUILD: pip install maturin
          CIBW_BUILD_FRONTEND: build
      
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish:
    name: Publish Release
    needs: [release-rust, release-python]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish to crates.io
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish --allow-dirty
        continue-on-error: true
      
      - name: Merge wheels
        run: |
          mkdir -p dist
          cp artifacts/wheels-*/*.whl dist/
      
      - name: Build source distribution
        run: |
          pip install build
          python -m build --sdist
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true