name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: rust
          
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Update Python version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          VERSION=${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add pyproject.toml
          git commit -m "chore: sync Python version to $VERSION" || true
          git push
      
      - name: Create Release Tag
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}